const { Parser } = require('node-sql-parser');
const parser = new Parser();

/**
 * Validates a SQL query generated by the AI to ensure it is strictly a SELECT statement.
 * This is the "Code-Level Blocking" security layer.
 * 
 * @param {string} sql - The raw SQL query string generated by the LLM
 * @returns {string} - The validated SQL string (sometimes slightly formatted by the parser)
 * @throws {Error} - Throws an error if the query attempts to modify data (UPDATE, DELETE, etc.)
 */
const validateSqlQuery = (sql) => {
    try {
        // Parse the SQL string into an Abstract Syntax Tree (AST) for MySQL
        const ast = parser.astify(sql, { database: 'MySQL' });
        
        // The AST can be an array if there are multiple statements (e.g., SELECT * FROM a; SELECT * FROM b;)
        const statements = Array.isArray(ast) ? ast : [ast];

        for (const statement of statements) {
            // Strictly enforce that every statement is a SELECT query
            if (statement.type.toUpperCase() !== 'SELECT') {
                throw new Error(`SECURITY ALERT: AI attempted to execute a non-SELECT query (${statement.type}). Query blocked.`);
            }
        }

        // Return the original SQL if it passes the security check
        return sql;
    } catch (error) {
        // If the parser fails to parse it (invalid syntax) or if our security check fails
        if (error.message.includes('SECURITY ALERT')) {
            throw error;
        }
        throw new Error(`Invalid SQL syntax generated by AI: ${error.message}`);
    }
};

module.exports = {
    validateSqlQuery
};
